# CONFIG FILE FOR TRAIN PIPELINE WITH DEFAULT ARGUMENTS


[Model]
architecture = "default" # ex : Conv5_FC3
multi_network = false
ssda_network = false

[Architecture]
# CNN
dropout = 0.0 # between 0 and 1
# architecture.n_layers = 4
# VAE
latent_space_size = 128
feature_size = 1024
n_conv = 4
io_layer_channels = 8
recons_weight = 1
kl_weight = 1
normalization = "batch"

[Classification]
selection_metrics = ["loss"]
label = "diagnosis"
label_code = {}
selection_threshold = 0.0 # Will only be used if num_networks != 1
loss = "CrossEntropyLoss"

[Regression]
selection_metrics = ["loss"]
label = "age"
loss = "MSELoss"

[Reconstruction]
selection_metrics = ["loss"]
loss = "MSELoss"

[Computational]
gpu = true
n_proc = 2
batch_size = 8
evaluation_steps = 0
fully_sharded_data_parallel = false
amp = false

[Reproducibility]
seed = 0
deterministic = false
compensation = "memory" # Only used if deterministic = true
track_exp = ""

[Transfer_learning]
transfer_path = ""
transfer_selection_metric = "loss"
nb_unfrozen_layer = 0

[Mode]
# require to manually generate preprocessing json
use_extracted_features = false

[Data]
multi_cohort = false
diagnoses = ["AD", "CN"]
baseline = false
normalize = true
data_augmentation = false
sampler = "random"
size_reduction=false
size_reduction_factor=2
caps_target = ""
tsv_target_lab = ""
tsv_target_unlab = ""
preprocessing_dict_target = ""

[Cross_validation]
n_splits = 0
split = []

[Optimization]
optimizer = "Adam"
epochs = 20
learning_rate = 1e-4
adaptive_learning_rate = false
weight_decay = 1e-4
patience = 0
tolerance = 0.0
accumulation_steps = 1
profiler = false
save_all_models = false

[Informations]
emissions_calculator = false
