# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_checkout:
      # Skip the build if the latest commit message contains
      # "[skip ci]", "[skip doc]", or "[only tests]".
      - (git --no-pager log --pretty="tformat:%s -- %b" -1 | paste -s -d " " | grep -Eviq "\[skip ci\]|\[skip doc\]|\[only tests\]") || exit 183
    post_install:
      - pip install poetry
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs

sphinx:
  configuration: docs/conf.py
