# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_checkout:
      - |
        COMMIT_MSG=$(git --no-pager log --pretty="format:%s %b" -1)
        echo "Commit message: $COMMIT_MSG"
        if echo "$COMMIT_MSG" | grep -Eiq "\[skip ci\]|\[skip doc\]|\[only tests\]|\[only gpu\]"; then
          echo "Skipping build due to commit flag."
          exit 183
        fi
    post_install:
      - pip install poetry
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs

sphinx:
  configuration: docs/conf.py
