# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      # Install Poetry
      - pip install poetry
      # Do not use virtual environments
      - poetry config virtualenvs.create false
      # Install docs group of dependencies
      - poetry install --only docs

mkdocs:
  configuration: mkdocs.yml
