[tool.poetry]
name = "clinicadl"
version = "2.0.0"
description = "open-source Python library for reproducible deep learning in neuroimaging"
license = "MIT"
authors = ["ARAMIS Lab"]
maintainers = ["ARAMIS Lab <aramislab.fr@gmail.com>"]
readme = "README.md"
homepage = "https://clinicadl.readthedocs.io"
repository = "https://github.com/aramis-lab/clinicadl.git"
documentation =  "https://clinicadl.readthedocs.io"
keywords = [
    "bids",
    "image processing",
    "deep learning",
    "neuroimaging",
    "neuroscience",
    "reproducibility",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
]

[tool.poetry.dependencies]
python = ">=3.10,<=3.14"
torch = "^2.3.0"
torchvision = "*"
pandas = "^2"
numpy = "^2"
scikit-learn = "^1"
joblib = "^1.2.0"
torchio = { version = "^0.20", extras = ["plot"]}
pydantic = "^2.7.0"
monai = "=1.5.0"
matplotlib =  "^3.9"
ipykernel = { version = "^6", optional = true }
notebook = { version = "^7", optional = true }
torchinfo = "^1.8.0"
scikit-image = "^0.25"

[tool.poetry.extras]
tutorials = ["matplotlib", "ipykernel", "notebook"]

[tool.poetry.group.dev]
optional = true
[tool.poetry.group.dev.dependencies]
pre-commit = "*"
pytest = "*"
pytest-timeout = "*"
pytest-xdist = "*"
pytest-cov = "^3.0.0"

[tool.poetry.group.docs]
optional = true
[tool.poetry.group.docs.dependencies]
sphinx = "^7"
furo = "^2024.8"
sphinx-design = "^0.6"
sphinx-autodoc-typehints = "^2"
sphinxcontrib-bibtex = "^2.6.4"
sphinx-copybutton = "^0.5.2"
sphinx-gallery = "^0.19"
autodoc-pydantic = "^2.2.0"
myst-parser = "^4"
nbsphinx = "^0.9.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py38"
line-length = 88

[tool.ruff.lint]
select = [
    "E",
    "W",
    "I",
]
ignore = ["E203", "E501"]

[tool.ruff.lint.isort]
known-first-party = ["clinicadl"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.per-file-ignores]
"examples/*.py" = ["E402"]  # import not a the beginning

[tool.coverage.run]
source = ["clinicadl"]
parallel = true
branch = true

[tool.coverage.report]
show_missing = true

[tool.codespell]
summary = ''
skip = ".git,LICENSE.txt,*.m,clinicadl/resources/config/train_config.toml"
quiet-level = 3
ignore-words-list = "nd,fwe,commun,fo,te,artic,ressources,adn"
