blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/aramis-lab/clinicadl/discussions/new/choose
    about: Ask questions and discuss with other ClinicaDL community members
