
[Model]
architecture = "AE_Conv4_FC3"
multi_network = false

[Architecture]
dropout = 0.0

[Classification]


[Regression]


[Reconstruction]
selection_metrics = ["loss"]
loss = "L1Loss"

[Computational]
gpu = true
n_proc = 2
batch_size = 8
evaluation_steps = 0

[Reproducibility]
seed = 0
deterministic = false

[Transfer_learning]
transfer_path = ""
transfer_selection_metric = ""

[Mode]
use_extracted_features = false

[Data]
diagnoses = ["AD", "CN"]
baseline = false
normalize = true
data_augmentation = []
sampler = "random"
size_reduction = false

[Cross_validation]
n_splits = 2
split = ["1"]

[Optimization]
optimizer = "Adam"
epochs = 5
learning_rate = 0.0001
weight_decay = 0.0001
patience = 0
tolerance = 0.0
accumulation_steps = 1
profiler = false