# CONFIG FILE FOR TRAIN PIPELINE WITH DEFAULT ARGUMENTS

[Meta_parametre]
info = """
Commentaire
""" # Sera écrit dans le train.log

[Model]
architecture = "VAE"
mutli = false

# CNN
architecture.dropout = 0.0 # between 0 and 1
# architecture.n_layers = 4
# VAE
architecture.latent_space_dimension = 64
architecture.latent_space_size = 2

# [Metrics]
# selection_metrics = [""]
# optimization_metric = "CE"

[Classification]
classification_selection_metrics = ["BA", "PRECISION"]
classification_optimization_metric = "CE"

[Regression]
classification_selection_metrics = [""]
classification_optimization_metric = "MSE"

[Reconstruction]
classification_selection_metrics = [""]
classification_optimization_metric = "MSE"
latent_space_size = 64
latent_space_dimension = 2

[Computational]
use_gpu = true
n_proc = 2
batch_size = 2
evaluation_steps = 0

[Transfert_learning]
transfer_path = "/path/to/maps"
transfer_selection_metric = "loss"

[Mode]
# require to manually generate preprocessing json
use_extracted_features = false

[Data]
multi_cohort = false
diagnoses = ["AD", "CN"]
baseline = false
normalize = false
data_augmentation = false
sampler = "random"

[Cross_validation]
n_splits = 0
split = []

[Optimization]
epochs = 20
learning_rate = 1e-4
weight_decay = 1e-4
patience = 0
tolerance = 0.0
accumulation_steps = 1
