name: Test

on:
  push:
    branches: ["dev", "refactoring", "clinicadl_v2"]
  pull_request:
    branches: ["dev", "refactoring", "clinicadl_v2"]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  POETRY_VERSION: "1.8.3"
  PREFERRED_PYTHON_VERSION: "3.12"

jobs:
  cpu-unit-tests:
    name: Unit tests on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
    steps:
      - uses: actions/checkout@v4
      - uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Run unit tests
        run: make unit-tests

  gpu-unit-tests:
    name: GPU unit tests (Python)
    runs-on:
      - self-hosted
      - gpu
    steps:
      - uses: actions/checkout@v4
      - uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry
      - name: Run unit tests
        run: make gpu-unit-tests

  # multi-gpu-unit-tests:
  #   name: Multi-GPUs unit tests (Python ${{ env.PREFERRED_PYTHON_VERSION }})
  #   runs-on:
  #     - self-hosted
  #     - multi-gpu
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: snok/install-poetry@v1
  #       with:
  #         version: ${{ env.POETRY_VERSION }}
  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ env.PREFERRED_PYTHON_VERSION }}
  #         cache: poetry
  #     - name: Run unit tests
  #       run: make multi-gpu-unit-tests

  # cpu-functional-test:
  #   name: Functional tests (Python ${{ env.PREFERRED_PYTHON_VERSION }})
  #   runs-on:
  #     - self-hosted
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: snok/install-poetry@v1
  #       with:
  #         version: ${{ env.POETRY_VERSION }}
  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ env.PREFERRED_PYTHON_VERSION }}
  #         cache: poetry
  #     - name: Run functional tests
  #       run: make functional-tests

  # gpu-functional-test:
  #   name: GPU functional tests (Python ${{ env.PREFERRED_PYTHON_VERSION }})
  #   runs-on:
  #     - self-hosted
  #     - gpu
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: snok/install-poetry@v1
  #       with:
  #         version: ${{ env.POETRY_VERSION }}
  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ env.PREFERRED_PYTHON_VERSION }}
  #         cache: poetry
  #     - name: Run functional tests
  #       run: make gpu-functional-tests