name: Generate Tests

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  POETRY_VERSION: '1.8.3'
  PYTHON_VERSION: '3.11'

jobs:
  test-generate:
    runs-on:
      - self-hosted
      - Linux
      - ubuntu
    steps:
      - uses: actions/checkout@v4
      - uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: false
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Run tests for generate task
        run: |
          make env.conda
          source /builds/miniconda3/etc/profile.d/conda.sh
          conda activate "${{ github.workspace }}"/env
          make install
          cd tests
          poetry run pytest --verbose \
          --junitxml=./test-reports/test_generate_report.xml \
          --disable-warnings \
          --verbose \
          --basetemp=$HOME/tmp/generate \
          --input_data_directory=/mnt/data/data_ci \
          test_generate.py
      - name: Cleaning
        run: |
          rm -rf $HOME/tmp/generate
